services:
  - type: web
    name: nutrition-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
    autoDeploy: true
    branch: main
    rootDir: .
    # Updated: Fixed meal creation API endpoint - 2025-01-05
    # Force deployment trigger - version 1.0.10
    # Deployment ID: 20250105-009
