services:
  - type: web
    name: nutrition-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
    autoDeploy: true
    branch: main
    # Updated: Fixed registration and onboarding flow - 2025-01-05
